// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package zebraprinting;

@net.sf.jni4net.attributes.ClrType
public class Class2 extends system.Object implements zebraprinting.ICallClass {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Class2(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Class2() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        zebraprinting.Class2.__ctorClass20(this);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;ILSystem/String;)V")
    public Class2(java.lang.String _name, int _age, java.lang.String _phoneNum) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        zebraprinting.Class2.__ctorClass21(this, _name, _age, _phoneNum);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorClass20(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;ILjava/lang/String;)V")
    private native static void __ctorClass21(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String _name, int _age, java.lang.String _phoneNum);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ILSystem/String;)V")
    public native void setInfo(java.lang.String _name, int age, java.lang.String _phoneNum);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void showInfo();
    
    public static system.Type typeof() {
        return zebraprinting.Class2.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        zebraprinting.Class2.staticType = staticType;
    }
    //</generated-proxy>
}
