// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package zebraprinting;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class ICallClass_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return zebraprinting.ICallClass_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        zebraprinting.ICallClass_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __ICallClass extends system.Object implements zebraprinting.ICallClass {
    
    protected __ICallClass(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ILSystem/String;)V")
    public native void setInfo(java.lang.String _name, int age, java.lang.String _phoneNum);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void showInfo();
}
//</generated-proxy>
