// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package zebraprinting;

@net.sf.jni4net.attributes.ClrInterface
public interface ICallClass {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ILSystem/String;)V")
    void setInfo(java.lang.String _name, int age, java.lang.String _phoneNum);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void showInfo();
    //</generated-interface>
}
