//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraPrinting {
    
    
    #region Component Designer generated code 
    public partial class Class2_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ZebraPrinting.@__Class2.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ZebraPrinting.Class2), typeof(global::ZebraPrinting.Class2_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ZebraPrinting.Class2), typeof(global::ZebraPrinting.Class2_))]
    internal sealed partial class @__Class2 : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Class2(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ZebraPrinting.@__Class2.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Class2);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setInfo", "setInfo0", "(Ljava/lang/String;ILjava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "showInfo", "showInfo1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorClass20", "__ctorClass20", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorClass21", "__ctorClass21", "(Lnet/sf/jni4net/inj/IClrProxy;Ljava/lang/String;ILjava/lang/String;)V"));
            return methods;
        }
        
        private static void setInfo0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle _name, int age, global::net.sf.jni4net.utils.JniLocalHandle _phoneNum) {
            // (Ljava/lang/String;ILjava/lang/String;)V
            // (LSystem/String;ILSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.Class2 @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ZebraPrinting.Class2>(@__env, @__obj);
            ((global::ZebraPrinting.ICallClass)(@__real)).setInfo(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _name), age, global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _phoneNum));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void showInfo1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.Class2 @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ZebraPrinting.Class2>(@__env, @__obj);
            ((global::ZebraPrinting.ICallClass)(@__real)).showInfo();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorClass20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.Class2 @__real = new global::ZebraPrinting.Class2();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorClass21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle _name, int _age, global::net.sf.jni4net.utils.JniLocalHandle _phoneNum) {
            // (Ljava/lang/String;ILjava/lang/String;)V
            // (LSystem/String;ILSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.Class2 @__real = new global::ZebraPrinting.Class2(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _name), _age, global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _phoneNum));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ZebraPrinting.@__Class2(@__env);
            }
        }
    }
    #endregion
}
