//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraPrinting {
    
    
    #region Component Designer generated code 
    public partial class ICallClass_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ZebraPrinting.@__ICallClass.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ZebraPrinting.ICallClass), typeof(global::ZebraPrinting.ICallClass_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ZebraPrinting.ICallClass), typeof(global::ZebraPrinting.ICallClass_))]
    internal sealed partial class @__ICallClass : global::java.lang.Object, global::ZebraPrinting.ICallClass {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setInfo0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_showInfo1;
        
        private @__ICallClass(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ZebraPrinting.@__ICallClass.staticClass = @__class;
            global::ZebraPrinting.@__ICallClass.j4n_setInfo0 = @__env.GetMethodID(global::ZebraPrinting.@__ICallClass.staticClass, "setInfo", "(Ljava/lang/String;ILjava/lang/String;)V");
            global::ZebraPrinting.@__ICallClass.j4n_showInfo1 = @__env.GetMethodID(global::ZebraPrinting.@__ICallClass.staticClass, "showInfo", "()V");
        }
        
        public void setInfo(string _name, int age, string _phoneNum) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::ZebraPrinting.@__ICallClass.j4n_setInfo0, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, _name), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(age), global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, _phoneNum));
            }
        }
        
        public void showInfo() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::ZebraPrinting.@__ICallClass.j4n_showInfo1);
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ICallClass);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setInfo", "setInfo0", "(Ljava/lang/String;ILjava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "showInfo", "showInfo1", "()V"));
            return methods;
        }
        
        private static void setInfo0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle _name, int age, global::net.sf.jni4net.utils.JniLocalHandle _phoneNum) {
            // (Ljava/lang/String;ILjava/lang/String;)V
            // (LSystem/String;ILSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.ICallClass @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::ZebraPrinting.ICallClass>(@__env, @__obj);
            @__real.setInfo(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _name), age, global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, _phoneNum));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void showInfo1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ZebraPrinting.ICallClass @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::ZebraPrinting.ICallClass>(@__env, @__obj);
            @__real.showInfo();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ZebraPrinting.@__ICallClass(@__env);
            }
        }
    }
    #endregion
}
